if (!isServer) exitWith {};

_unitTypes_heavy_RHS_AFRF = [
	"rhs_msv_emr_at",
	"rhs_msv_emr_arifleman_rpk",
	"rhs_msv_emr_arifleman",
	"rhs_msv_emr_efreitor",
	"rhs_msv_emr_engineer",
	"rhs_msv_emr_grenadier_rpg",
	"rhs_msv_emr_strelok_rpg_assist",
	"rhs_msv_emr_junior_sergeant",
	"rhs_msv_emr_machinegunner",
	"rhs_msv_emr_machinegunner_assistent",
	"rhs_msv_emr_marksman",
	"rhs_msv_emr_medic",
	"rhs_msv_emr_officer",
	"rhs_msv_emr_officer_armored",
	"rhs_msv_emr_rifleman",
	"rhs_msv_emr_grenadier",
	"rhs_msv_emr_LAT",
	"rhs_msv_emr_RHsG2",
	"rhs_msv_emr_sergeant"
];

_unitTypes_light_RHS_GREF = [
	"rhsgref_ins_grenadier_rpg",
	"rhsgref_ins_arifleman_rpk",
	"rhsgref_ins_commander",
	"rhsgref_ins_machinegunner",
	"rhsgref_ins_medic",
	"rhsgref_ins_militiaman_mosin",
	"rhsgref_ins_squadleader",
	"rhsgref_ins_rifleman",
	"rhsgref_ins_rifleman_akm",
	"rhsgref_ins_rifleman_aks74",
	"rhsgref_ins_rifleman_aksu",
	"rhsgref_ins_rifleman_RPG26",
	"rhsgref_ins_grenadier",
	"rhsgref_ins_saboteur",
	"rhsgref_ins_engineer",
	"rhsgref_ins_sniper",
	"rhsgref_ins_spotter"
];

_vehicleTypes_heavy_RHS_AFRF = [
	"rhs_tigr_msv",
	"rhs_tigr_3camo_msv",
	"rhs_tigr_m_msv",
	"rhs_tigr_m_3camo_msv",
	"rhs_tigr_sts_msv",
	"rhs_tigr_sts_3camo_msv",
	"rhs_btr60_msv",
	"rhs_btr70_msv",
	"rhs_btr80_msv",
	"rhsgref_BRDM2UM_HQ_msv",
	"rhsgref_BRDM2_msv",
	"rhsgref_ins_bmd1", 
	"rhsgref_ins_bmd1p", 
	"rhsgref_ins_bmd2", 
	"rhsgref_ins_bmp1", 
	"rhsgref_ins_bmp1d", 
	"rhsgref_ins_bmp1k", 
	"rhsgref_ins_bmp1p", 
	"rhsgref_ins_bmp2e", 
	"rhsgref_ins_bmp2", 
	"rhsgref_ins_bmp2k", 
	"rhsgref_ins_bmp2d", 
	"rhs_bmp1_msv", 
	"rhs_bmp1d_msv", 
	"rhs_bmp1k_msv", 
	"rhs_bmp1p_msv", 
	"rhs_bmp2e_msv", 
	"rhs_bmp2_msv", 
	"rhs_bmp2d_msv", 
	"rhs_bmp2k_msv", 
	"rhs_bmp3_msv", 
	"rhs_bmp3_late_msv", 
	"rhs_bmp3m_msv", 
	"rhs_bmp3mera_msv", 
	"rhs_Ob_681_2", 
	"rhs_prp3_msv", 
	"rhs_brm1k_msv", 
	"rhs_bmd1", 
	"rhs_bmd1k", 
	"rhs_bmd1p", 
	"rhs_bmd1pk", 
	"rhs_bmd1r", 
	"rhs_bmd2", 
	"rhs_bmd2k", 
	"rhs_bmd2m", 
	"rhs_bmd4_vdv", 
	"rhs_bmd4m_vdv", 
	"rhs_bmd4ma_vdv", 
	"rhs_t72ba_tv", 
	"rhs_t72bb_tv", 
	"rhs_t72bc_tv", 
	"rhs_t72bd_tv", 
	"rhs_t72be_tv", 
	"rhs_t80", 
	"rhs_t80a", 
	"rhs_t80b", 
	"rhs_t80bk", 
	"rhs_t80bv", 
	"rhs_t80bvk", 
	"rhs_t80u", 
	"rhs_t80u45m", 
	"rhs_t80ue1", 
	"rhs_t80uk", 
	"rhs_t80um", 
	"rhs_t90_tv", 
	"rhs_t90a_tv", 
	"rhs_t90am_tv", 
	"rhs_t90saa_tv", 
	"rhs_t90sab_tv", 
	"rhs_t90sm_tv", 
	"rhs_sprut_vdv", 
	"rhssaf_army_o_t72s"
];

_vehicleTypes_heavy_naval_RHS_AFRF = [
	
];

_vehicleTypes_light_RHS_GREF = [
	"rhsgref_ins_uaz",
	"rhsgref_ins_uaz_dshkm",
	"rhsgref_ins_uaz_open",
	"rhsgref_ins_uaz_spg9",
	"rhsgref_BRDM2UM_ins",
	"rhsgref_ins_gaz66",
	"rhsgref_ins_gaz66o",
	"rhsgref_ins_ural",
	"rhsgref_ins_ural_open",
	"rhsgref_ins_zil131",
	"rhsgref_ins_zil131_open",
	"rhs_kamaz5350_msv",
	"rhs_kamaz5350_open_msv",
	"rhs_kraz255b1_msv",
	"rhs_kraz255b1_cargo_open_msv",
	"RHS_Ural_MSV_01",
	"RHS_Ural_Open_MSV_01",
	"rhs_zil131_msv",
	"rhs_zil131_open_msv",
	"rhsgref_BRDM2UM_msv",
	"rhssaf_army_o_pts"
];

_vehicleTypes_light_naval_RHS_AFRF = [
	
];